version: 2

models:
  - name: bridge_game_team
    columns:
      - name: game_key
        tests:
          - relationships:
              to: ref('fact_games')
              field: game_key
      - name: team_key
        tests:
          - relationships:
              to: ref('dim_teams')
              field: team_key
  - name: dim_teams
    columns:
      - name: team_key
        tests:
          - unique
          - not_null

  - name: dim_competitions
    columns:
      - name: competition_key
        tests:
          - unique
          - not_null

  - name: dim_competition_seasons
    columns:
      - name: competition_season_key
        tests:
          - unique
          - not_null

  - name: dim_dates
    columns:
      - name: date_day
        tests:
          - unique
          - not_null

  - name: fact_games
    columns:
      - name: game_key
        tests:
          - unique
          - not_null
      - name: competition_key
        tests:
          - relationships:
              to: ref('dim_competitions')
              field: competition_key
      - name: competition_season_key
        tests:
          - relationships:
              to: ref('dim_competition_seasons')
              field: competition_season_key


  - name: fact_standings
    columns:
      - name: standings_key
        tests:
          - unique
          - not_null
      - name: team_key
        tests:
          - relationships:
              to: ref('dim_teams')
              field: team_key
      - name: competition_key
        tests:
          - relationships:
              to: ref('dim_competitions')
              field: competition_key
      - name: competition_season_key
        tests:
          - relationships:
              to: ref('dim_competition_seasons')
              field: competition_season_key
